version: 2

models:
  - name: fact_products
    description: "플랫폼별 실버 상품 데이터를 통합한 골드 계층 상품 테이블"
    columns:
      - name: product_uid
        description: "플랫폼 + product_id를 조합한 유일 식별자 (예: naver_123456)"
        tests:
          - unique
          - not_null

      - name: product_id
        description: "원본 플랫폼에서의 상품 ID"

      - name: name
        description: "상품 이름"

      - name: brand
        description: "상품 브랜드명"

      - name: price
        description: "상품 가격 (정가 또는 판매가)"

      - name: rating
        description: "리뷰 평균 평점 (소수점 1자리, musinsa는 0~100을 0~5로 변환)"

      - name: review_count
        description: "상품에 대한 리뷰 수"

      - name: category
        description: "상품 카테고리명"

      - name: platform
        description: "데이터 출처 플랫폼"

      - name: scraped_at
        description: "해당 상품이 수집된 시각 (UTC)"

  - name: fact_reviews
    description: "플랫폼별 실버 리뷰 데이터를 통합한 골드 계층 리뷰 테이블"
    columns:
      - name: review_uid
        description: "플랫폼 + review_id를 조합한 유일 식별자 (예: musinsa_987654)"
        tests:
          - unique
          - not_null

      - name: review_id
        description: "원본 플랫폼에서의 리뷰 ID"
        tests:
          - not_null

      - name: product_id
        description: "해당 리뷰가 작성된 상품의 ID (원본 기준)"
        tests:
          - not_null

      - name: star
        description: "리뷰 별점 (정수형 0~5점으로 통일)"

      - name: content
        description: "리뷰 본문 텍스트"

      - name: created_at
        description: "리뷰 작성일 (DATE 형식: yyyy-mm-dd)"
        tests:
          - not_null

      - name: category
        description: "해당 리뷰 상품의 카테고리명"

      - name: platform
        description: "리뷰가 수집된 플랫폼명 (예: oliveyoung, naver, musinsa)"
        tests:
          - not_null

      - name: scraped_at
        description: "해당 리뷰가 수집된 시각 (UTC)"
        tests:
          - not_null
